### ISSUE TITLE
get_particle_trace not working

### ISSUE THREAD

**Issue by avi-xd** [softmatterlab/Quantitative-Microplankton-Tracker#1]
Hi, I am trying to run " 3-example_analysis" file on my system,  but I am getting error with the function `get_particle_trace`. How can I resolve the error `AttributeError: module 'deeptrack' has no attribute 'get_particle_trace'`.

**Comment by harbac** [comment]
Hi! Thanks for reaching out. Could you check if you have a different version of deeptrack installed in your system? The version of deeptrack that is used for this project is included in the repository, and it will be loaded by default. I have just re-tested the example on Colab and it works as it is without any modifications.

**P.S.** Current versions of numpy may not be able to run the following line `print('Particles', np.shape(particles), 'completed traces', np.shape(completed_traces))` in cell 4.1. So, you should comment that line out if it throws an error.
